spring.application.name=online-election

spring.datasource.url=jdbc:mysql://localhost:3306/online_election?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Aa123456!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

aes.secret=1234567890123456
aes.iv=abcdefghijklmnop

upload.path=D:/online-election/uploads/
spring.web.resources.static-locations=file:D:/online-election/uploads/

server.port=8080
